language: python
notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

python:
    - "3.8"

script:
  - python ./dockerlief/main.py list
  - python ./.github/main.py


cache:
  directories:
    - $HOME/docker
